# -*- coding: utf-8 -*-
"""
Created on Sun Nov  6 17:20:56 2022

@author: Jeroigoldi
"""

import numpy as np
import matplotlib.pyplot as plt
import soundfile as sf
from scipy import signal

def sweep(t, f_start, f_end, sample_rate):
    """
    Generates a frequency sweep given the duration and the frequency interval.
    
    Parameters
    ----------
    t : float
        Lenght in seconds of the sweep.
    f_start : float
        Lowest frequency in Hertz of the sweep.
    f_end : float
        Highest frequency in Hertz of the sweep.
    sample_rate : float
        Sample rate frequency in Hertz of the sweep.

    Returns
    -------
    time : ndarray
        Array that contains the time values.
    sweep_signal : array_like
        Array that contains the magnitude values of the sweep created.
                
    """
    time = np.linspace(0, t, sample_rate*t)
    k = (t*2*np.pi*f_start)/(np.log(f_end/f_start))
    l = t/np.log(f_end/f_start)
    sweep_signal = np.sin(k*(np.exp(time/l))-1)
    
    return (time, sweep_signal)

def plot(x, functions, names, x_label="", y_label="", x_limits=(), y_limits=(), figsize=(15, 10), logx_scale=False, fontsize = 14, save=False, filename="graficos/plot.png", **kwargs):
    '''
    Plots any amount of functions on the same plot, given the same array for the horizontal axis.

    Parameters
    ----------
    x : numpy.ndarray
        The domain of the funtions in the graph.
    functions : list(numpy.ndarray)
        The list of arrays with the functions to plot. 
    names : list(str)
        The list with a descriptive name for each function. They will be placed in the figure legend.
    x_label : str, optional
        The label of the horizontal axis. It should include the unit when it corresponds. Only shown when given.
    y_label : str, optional
        The label of the vertical axis. It should include the unit when it corresponds. Only shown when given.
    x_limits : tuple, optional
        The limits of x axis of the graph. If not given, the automatic limits generated by matplotlib are displayed.
    y_limits : tuple, optional
        The limits of y axis of the graph. If not given, the automatic limits generated by matplotlib are displayed.
    logx_scale : bool, optional
        If True, the function uses the semilogx() function to plot instead of plot(). Default is False.
    figsize: tuple, optoinal
        Sets the figure size of the plot when created. Default is (15, 10).
    fontsize : int, optional
        The fontsize of the axis and legend labels. The default is 14.
    save : boolean, optional
        If True, saves the plot. 
    filename : str, optional
        The path where the plot will be saved if save=True. Default is "graficos/plot.png".
    **kwargs : dict
        Any parameter that the function matplotlib.pyplot.plot() permits can be configured here. 

    Returns
    -------
    None.

    '''
    plt.figure(figsize=figsize)    
    if logx_scale:
        for i in range(0, len(functions)):
            plt.semilogx(x, functions[i], label=names[i], **kwargs)
        plt.xticks([16, 31.5, 63, 125, 250, 500, 1000, 2000, 4000, 8000, 16000],['16', '31.5','63','125','250','500','1k','2k','4k','8k','16k'])
    else:
        for i in range(0, len(functions)):
            plt.plot(x, functions[i], label=names[i], **kwargs)
        
    if x_label != "":
        plt.xlabel(x_label, fontsize=fontsize)
    if y_label != "":
        plt.ylabel(y_label, fontsize=fontsize)
    if x_limits != ():
        plt.xlim(x_limits)
    if y_limits != ():
        plt.ylim(y_limits)      
    plt.legend(fontsize=fontsize)
    plt.grid()
    if save:
        plt.savefig(filename)
        
def bar(x, y, names, x_label = "", y_label = "", y_limits=(), y_ticks=[], figsize=(15, 10), fontsize = 14, save=False, filename="graficos/bar.png", **kwargs):
    '''
    Plots any amount of array on the same bar graph, given the same array for the horizontal axis.

    Parameters
    ----------
    x : array_like
        The array with the values for the horizontal values, the name of each bar. If numeric and not linear scale, may not work properly.
        In that case, parse to string.
    y : array_like
        An array of arrays containing the values of each bar.
    names : TYPE
        DESCRIPTION.
    names : list(str)
        The list with a descriptive name for each function. They will be placed in the figure legend.
    x_label : str, optional
        The label of the horizontal axis. It should include the unit when it corresponds. Only shown when given.
    y_label : str, optional
        The label of the vertical axis. It should include the unit when it corresponds. Only shown when given.
    y_limits : tuple, optional
        The limits of y axis of the graph. If not given, the automatic limits generated by matplotlib are displayed.
    y_ticks : array, optional
        The ticks of y axis of the graph. If not given, the automatic ticks generated by matplotlib are displayed.
    figsize: tuple, optoinal
        Sets the figure size of the plot when created. Default is (15, 10).
    fontsize : int, optional
        The fontsize of the axis and legend labels. The default is 14.
    save : boolean, optional
        If True, saves the plot. 
    filename : str, optional
        The path where the plot will be saved if save=True. Default is "graficos/bar.png".
    **kwargs : dict
        Any parameter that the function matplotlib.pyplot.bar() permits can be configured here. 

    Returns
    -------
    None.

    '''
    plt.figure(figsize=figsize)
    for i in range(0, len(y)):
        plt.bar(x, y[i], label=names[i], **kwargs)
        
    if x_label != "":
        plt.xlabel(x_label, fontsize=fontsize)
    if y_label != "":
        plt.ylabel(y_label, fontsize=fontsize)
    if y_limits != ():
        plt.ylim(y_limits)
    if y_ticks != []:
        plt.yticks(y_ticks)
    plt.legend(fontsize=fontsize)
    plt.grid()
    if save:
        plt.savefig(filename) 
    
def dbfft(x, fs, win=None):
    """
    
    Transforms function using the FFT and shows the amplitude in dBfs. 
    Parameters
    ----------
    x : numpy.ndarray
        The function to transform.
    fs : int.
        Sample rate of the function x.

    Returns
    -------
    Tuple with frequencies and function values of the FFT in dB.

    """
    N = len(x)  # Length of input sequence

    if win is None:
        win = np.ones(x.shape)
    if len(x) != len(win):
            raise ValueError('Signal and window must be of the same length')
    x = x * win

    # Calculate real FFT and frequency vector
    sp = np.fft.rfft(x)
    freq = np.arange((N / 2) + 1) / (float(N) / fs)

    # Scale the magnitude of FFT by window and factor of 2,
    # because we are using half of FFT spectrum.
    s_mag = np.abs(sp) * 2 / np.sum(win)

    # Convert to dBFS
    ref = s_mag.max()
    s_dbfs = 20 * np.log10(s_mag/ref)

    return freq, s_dbfs

def sumsins(sr, t, *freqs):
    '''
    Returns a function formed by a sum of sine waves.

    Parameters
    ----------
    sr : int
        Sample-rate of the signal(s) to generate.
    t : float
        The length in seconds of the time vector of the signal to generate.
    freqs : exploited list
        Exploited list of the frequency values of each signal to generate. 

    Returns
    -------
    t : ndarray
        Array that contains the time values.
    output : array_like
        Array that contains the values of the generated signal.

    '''
    t = np.linspace(0, t, sr*t)
    output = 0
    for freq in freqs:
        y = np.sin(2*np.pi*freq*t)
        output = output + y
    return t, output

def RMS(signal):
    '''
    Returns the root mean square of a signal.

    Parameters
    ----------
    signal : array_like
        The array to which the RMS will be calculated.

    Returns
    -------
    rms : float
        The RMS of the given signal.

    '''
    rms = np.sqrt(np.sum(signal**2) / len(signal))
    return rms

def calibrate_rec(rec_path, interval, ref):
    '''
    Calibrates a recorded signal to Pascals given the RMS of the calibration recording of the same mic.
    Also, shortens the audio to a selected interval.

    Parameters
    ----------
    rec_path : str
        The path of the file with the recording
    interval : tuple(int)
        It should have the starting and ending points of the recording, in seconds.
        The values must be between 0 and the duration of the signal.
    ref : int
        The RMS of the calibration signal given a calibration of 94 dB. If it was calibrated 
        to another value, ref should be the RMS divided by that value (in Pa).

    Returns
    -------
    array_like
        The calibrated signal in Pascals.

    '''
    rec_raw, fs = sf.read(rec_path) 
    rec = rec_raw[interval[0]*fs:interval[1]*fs]
    return rec/ref

def Leq(s):
    '''
    Returns the equivalent pressure level of a signal in time.

    Parameters
    ----------
    s : array_like
        The signal in time to which the Leq will be calculated. The values should be in dB SPL.

    Returns
    -------
    leq : float
        The Leq of the signal values. If these are is dB SPL, this value will be too.

    '''
    leq = 10*np.log10(np.sum(10**(s/10)) / len(s))
    return leq

def sos_filter_bank(b, freqs_m, N, sr, G=2):
    '''
    Generates a 'sos' bandpass butterworth filter bank given the array of central frequencies and the divison of octave 'b'.
    For more info about the filter, look into the scipy.signal.butter documentation.

    Parameters
    ----------
    b : int
        The division of octave that the filters will cover. If a full octave is required, b = 1.
    freqs_m : array_like
        The array of central frequencies.
    N : int
        The order of the filter
    sr : int
        The sample rate that will be used to normalize the frequencies. This should be the same sr as the one 
        from the audio that will be filtered.
    G : float, optional
        The octave ratio. The ISO norm recommends using the base 10 ratio: 10^(3/10). The default is 2.

    Returns
    -------
    filters : array_like
        An array of the second order filters generated.

    '''
    filters = [] 
    for f_m in freqs_m:
        f_1 = G**(-1/(2*b)) * f_m     #frec inferior
        f_2 = G**(1/(2*b)) * f_m     #frec superior
        f_1_norm = f_1 / (sr/2)
        f_2_norm = f_2 / (sr/2)
        sos = signal.butter(N, [f_1_norm, f_2_norm], btype='bandpass', output='sos')
        filters.append(sos)
    return filters

def sos_filter_audio(s, *filters):
    '''
    Filters an audio signal with any amount of sos filters.

    Parameters
    ----------
    s : array_like
        The audio signal that will be filtered
    *filters : array_like
        The sos filters that will be used.

    Returns
    -------
    TYPE
        If only 1 filter is given, it returns the filtered audio, else returns an array with the 
        audio filtered by all the filters given.

    '''
    if len(filters) == 1:
        return signal.sosfilt(filters[0], s)
    else: 
        filtered_audio_bank = []
        for filt in filters:
            filtered_audio = signal.sosfilt(filt, s)
            filtered_audio_bank.append(filtered_audio)
        return filtered_audio_bank
    
def signal_to_SPL(s):
    '''
    Converts an array with pressure levels in Pa to db SPL.

    Parameters
    ----------
    s : array_like
        The array with pressure level values.

    Returns
    -------
    array_like
        The array with SPL values.

    '''
    p_ref = 2* 10**(-5)
    eps = np.finfo(float).eps
    P_norm = (abs(s) + eps) / p_ref 
    return 20 * np.log10(P_norm)

def magdb(x):
    """
    
    Transforms amplitude values to dBFS.
    Parameters
    ----------
    x : numpy.ndarray
        The function to transform.

    Returns
    -------
    xmagdb : numpy.ndarray
        Contains amplitude values of x in dBFS.

    """
    xmag = abs(x) / len(x)
    xmagnorm = xmag / np.max(abs(xmag))
    eps = np.finfo(float).eps
    xmagdb = 20*np.log10(xmagnorm + eps)
    return xmagdb 